config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "metrics#index"

  # get metrics
  get 'api/metrics'=>'metrics#getMetrics'

  # get metrics timeline hour
  get 'api/metrics/timeline'=>'metrics#timeline'

  # get metrics timeline day
  get 'api/metrics/timeline/day'=>'metrics#timelineDay'

  # get metrics timeline minutes
  get 'api/metrics/timeline/minute'=>'metrics#timelineMinute'

  #Resources routes
  resources :metrics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/metric.rb
class Metric < ApplicationRecord
    validates :name, presence: true,
                        length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
    def index
        @metrics = Metric.all
        # render json: @metrics
    end

    # get all metrics (API)
    def getMetrics
        @metrics = Metric.all
        render json: @metrics
    end
    
    #the metrics create form
    def new
        @metric = Metric.new
    end


    #Store the metric to the database
    def create
        # render plain: params[:metric].inspect
        @metric = Metric.new(metric_params)
        if(@metric.save)
            redirect_to @metric
        else
            render 'new'
        end
    end

    # This method validates the form data
    private def metric_params
        params.require(:metric).permit(:name, :value)
    end

    # show details of a specific metric
    def show
        @metric = Metric.find(params[:id])
    end

    # show the form of the metric to edit
    def edit
        @metric = Metric.find(params[:id])
    end
    
    #Store the metric to the database
    def update
        # render plain: params[:metric].inspect
        @metric = Metric.find(params[:id])
        if(@metric.update(metric_params))
            redirect_to @metric
        else
            render 'edit'
        end
    end

    # detete metric metric by id
    def destroy
        @metric = Metric.find(params[:id])
        @metric.destroy
        redirect_to metrics_path
    end

    # get averages of metrics per minute
    def timelineMinute
        metrics = Metric.all

        grouped_by_minute = metrics.group_by { |d| d[:created_at].strftime('%Y-%m-%d %H:%M') }
        # Calculate the average for each minute
        averages = {}
        grouped_by_minute.each do |minute, arry|
            arry.each do |metric|
                if averages[minute]
                    averages[minute][:count] += 1
                    averages[minute][:value] += metric.value
                else
                    averages[minute] = { count: 1, value: metric.value }
                end
            end
        end

        averages.each do |minute, data|
            averages[minute][:value] = averages[minute][:value]/data[:count]
        end

        # Format the data as an array of objects
        dataR = []
        averages.each do |minute, data|
            dataR << { minute: minute, value: data[:value] }
        end
        render json: dataR
    end

    # get the average per hour
    def timeline
        metrics = Metric.all

        # Calculate the average for each hour
        averages = {}
        metrics.each do |metric|
            hour = metric.created_at.beginning_of_hour
            if averages[hour]
                averages[hour][:count] += 1
                averages[hour][:value] += metric.value
            else
                averages[hour] = { count: 1, value: metric.value }
            end
        end

        averages.each do |hour, data|
            averages[hour][:value] = averages[hour][:value]/data[:count]
        end

        # Format the data as an array of objects
        dataR = []
        averages.each do |hour, data|
            dataR << { hour: hour, value: data[:value] }
        end
        render json: dataR
    end

    # get the average per day
    def timelineDay
        metrics = Metric.all

        # Calculate the average for each day
        averages = {}
        metrics.each do |metric|
            day = metric.created_at.beginning_of_day
            if averages[day]
                averages[day][:count] += 1
                averages[day][:value] += metric.value
            else
                averages[day] = { count: 1, value: metric.value }
            end
        end

        averages.each do |day, data|
            averages[day][:value] = averages[day][:value]/data[:count]
        end

        # Format the data as an array of objects
        dataR = []
        averages.each do |day, data|
            dataR << { day: day, value: data[:value] }
        end
        render json: dataR
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backoffice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%# # Bootstrap %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Backoffice</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <%# <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li> %>
              <li class="nav-item">
                <%= link_to 'List', '/', class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Add Metric', new_metric_path, class: "nav-link" %>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="flex-shrink-0" style="padding-top: 70px">
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/metrics/edit.html.erb
<h1>Edit metric</h1>

<%= form_for :metric, url: metric_path(@metric), data: { turbo: false }, method: :patch do |f|%>
    <% if @metric.errors.any? %>
        <% @metric.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"> <%= msg %> </div>
        <% end %>
    <% end %>
    <p>
        <%=f.label :name%> <br>
        <%=f.text_field(:name, {:class=>'form-control'}) %>
    </p>
    <p>
        <%=f.label :value%> <br>
        <%=f.text_field(:value, {:class=>'form-control'}) %>
    </p>
    <p>
        <%=f.submit :class=>'btn btn-primary' %> <br>
    </p>
<% end %>

app/views/metrics/index.html.erb
<h1>Metrics</h1>

<table class="table">
    <tr>
        <td>
            <b> Name </b>
        </td>
        <td>
            <b> Value </b>
        </td>
        <td>
            <b> Created At </b>
        </td>
        <td>
            <b> Action </b>
        </td>
    </tr>
    <% @metrics.each do |metric|%>
    <tr>
        <td>
            <%=metric.name%>
        </td>
        <td>
            <%=metric.value%>
        </td>
        <td>
            <%=metric.created_at%>
        </td>
        <td>
            <%= link_to "Edit", edit_metric_path(metric), :class=>'btn btn-primary' %>
            <%# <%= link_to "Delete", metric_path(metric),
                 method: :delete, 
                 data: {confirm: "Are you sure?"},
                 :class => 'btn btn-danger' %> %>

                 <%= button_to "delete", {:controller => :metrics,
      :action => 'destroy', data: {confirm: "Are you sure?"}, :id => metric.id }, :method => :delete,  :class => 'btn btn-danger'%>
        </td>
    </tr>
    <%end%>
</table>

app/views/metrics/new.html.erb
<h1>New metric</h1>

<%= form_for :metric, url: metrics_path, data: { turbo: false } do |f|%>
    <% if @metric.errors.any? %>
        <% @metric.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"> <%= msg %> </div>
        <% end %>
    <% end %>
    <p>
        <%=f.label :name%> <br>
        <%=f.text_field(:name, {:class=>'form-control'}) %>
    </p>
    <p>
        <%=f.label :value%> <br>
        <%=f.text_field(:value, {:class=>'form-control'}) %>
    </p>
    <p>
        <%=f.submit :class=>'btn btn-primary' %> <br>
    </p>
<% end %>

app/views/metrics/show.html.erb
<h2><%= @metric.name %></h2>
<p><%= @metric.value %></p>